spring.application.name=bookshop

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=bookshop;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=Qwert123
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

jwt.expiration=300000
jwt.secret=bookshop_11123085z349z39754783158t4683t583tg4f8g38vn471n4rv7316v7n4
