url=jdbc:mysql://localhost:3306/bookshop_app?serverTimeZone=UTC
username=username
password=password
changeLogFile=src/main/resources/db/changelog/db.changelog-master.yaml
driver=com.mysql.cj.jdbc.Driver