url=jdbc:sqlserver://localhost:1433;databaseName=bookshop;\
  encrypt=true;trustServerCertificate=true
username=sa
password=Qwert123
changeLogFile=src/main/resources/db/changelog/db.changelog-master.yaml
driver=com.microsoft.sqlserver.jdbc.SQLServerDriver


